### ISSUE TITLE
get_all() not implemented for pipelines

### ISSUE THREAD

**Issue by mariana-s-fernandes** [HubSpot/hubspot-api-python#183]
I would like to get all pipelines, but the method is not implemented for this object.
In the same way that I can pull all contacts:
`all_contacts = api_client.crm.contacts.get_all()`

I would like to have the equivalent for pipelines:
`all_pipelines = api_client.crm.pipelines.get_all()`

**Comment by alzheltkovskiy-hubspot** [comment]
Hi @mariana-s-fernandes.
As you can see in [documentation](https://developers.hubspot.com/docs/api/crm/pipelines), the pipelines includes APIs such as (`pipeline_api` and `pipeline_stages_api`) and so that there would be no confusion, the `get_all` method is called from any of them. This means, if you want to get all pipelines your request should looks like this:
```python
all_pipelines = api_client.crm.pipelines.pipelines_api.get_all()
```
Or if you want to get all pipeline stages:
```python
all_pipeline_stages = api_client.crm.pipelines.pipeline_stages_api.get_all()
```
I hope this information will be useful.

**Comment by mariana-s-fernandes** [comment]
Thanks @alzheltkovskiy-hubspot ! I will test it soon and will let you know!

**Comment by mariana-s-fernandes** [comment]
that work, thanks!!
