### ISSUE TITLE
properties in .crm.objects.get_all() call bloats query parameters

### ISSUE THREAD

**Issue by jcshott** [HubSpot/hubspot-api-python#334]
We use the `get_all()` call with properties to fetch a bunch of properties.

something like:

```
api_client.crm.objects.get_all(object_type='contacts', properties=['prop_1', 'prop_2'])
```

I have noticed that the query parameters are added as individual parameters, for example:
```
/crm/v3/objects/CONTACTS?limit=100&properties=<prop_1>&properties=<prop_2>
```
instead of a comma-separated list as defined in the API docs:
```
/crm/v3/objects/CONTACTS?limit=100&properties=<prop_1>,<prop_2>
```

This is bloating the URI length unnecessarily and could be causing some issues we are seeing

**Comment by alzheltkovskiy-hubspot** [comment]
Hi @jcshott! Could you share the documentation you’re using? Based on the documentation we have, everything is working as expected. Additionally, we have a few tips for improving how you fetch all contacts. It's recommended to use 
```api_client.crm.objects.contacts.get_all()```
as outlined in the [documentation](https://developers.hubspot.com/docs/api/crm/contacts).

Let me know if that works or if you'd like any changes!

**Comment by jcshott** [comment]
Hi - yes, we are utilizing this function: https://github.com/HubSpot/hubspot-api-python/blob/v7.0.0/hubspot/discovery/crm/objects/discovery.py#L59 (i.e. `api_client.crm.objects.get_all(object_type=object_type, properties=properties_list)` 

where object_type _could_ be one of a few different types. Contacts, Deals or one of a couple custom types we have.

We use this in a utility function we have to call hubspot with an object type and properties we need - since the basic `get_all()` only returns some properties, we have to ask for custom ones we want using the `properties` param.

when we call that - instead of one query param of `properties=<comma-separated-list-of-properties>` (like the [docs](https://developers.hubspot.com/beta-docs/reference/api/crm/objects/contacts#get-%2Fcrm%2Fv3%2Fobjects%2Fcontacts) indicate) we are seeing the API call as `/crm/v3/objects/CONTACTS?limit=100&properties=<prop_1>&properties=<prop_2>` where each property is a query param.

Would using the `api_client.crm.objects.contacts.get_all(properties=properties_list)` be any different than this?

I think it's because when the query params here: https://github.com/HubSpot/hubspot-api-python/blob/v7.0.0/hubspot/crm/contacts/api/basic_api.py#L460-L462 - the[ _call_api()](https://github.com/HubSpot/hubspot-api-python/blob/v7.0.0/hubspot/crm/contacts/api_client.py#L150) function turns [them into tuples](https://github.com/HubSpot/hubspot-api-python/blob/v7.0.0/hubspot/crm/contacts/api_client.py#L416C1-L418C1
) so each param is a new query parameter. 

That makes sense if the query parameters are different key/value pairs. but since this is just `properties` key and value is list of properties to get from Hubspot, it should be one query param.

I think if the collection_format wasn't `multi`: https://github.com/HubSpot/hubspot-api-python/blob/v7.0.0/hubspot/crm/contacts/api/basic_api.py#L462 then the format would be correct.

quick example:
```
query_params = [('properties', ['test1', 'test2'])]
collection_formats["properties"] = "multi"

parameters_to_tuples(query_params, collection_formats)
Out[]: [('properties', 'test1'), ('properties', 'test2')]

v.

parameters_to_tuples(query_params, collection_formats)
Out[]: [('properties', ['test1', 'test2'])]

```

in the second case - with no defined `collection_format`, the properties would be one query parameter of `propeties=<comma-separated-list>`


I understand it works as it is - its just bloating the request heavily by adding unnecessary query parameters.

**Comment by zkorelic** [comment]
We are experiencing the same issue. We are trying to fetch all our contacts with all their properties from the API, but since we have to include the entire list of properties in the call, it results in URI too long error.

Example:
`
contact_properties_list = api_client.crm.properties.core_api.get_all('contact').to_dict()['results']
contact_property_names = [prop['name'] for prop in contact_properties_list if prop['hidden'] != True] 

contacts = api_client.crm.contacts.get_all(properties=contact_property_names, associations=['DEAL', 'COMPANY'], limit=100, archived=False)
`

This throws an error `ApiException: (414) Reason: URI Too Long`.

I'm wondering if there's perhaps a more appropriate way we to retrieve all contacts with all their properties?

**Comment by alzheltkovskiy-hubspot** [comment]
Hey all. Since the code is generated automatically, we cannot change the multi parameter, as the changes would apply to all clients, even those that do not support it. In the future, we plan to address this, but for now, there is an interim solution for your case. We have added a new `api_request` API, which can help with your case in the [latest version of the SDK](https://github.com/HubSpot/hubspot-api-python/releases/tag/v11.0.0). Information on how to use `api_request` can be found in the README.
