### ISSUE TITLE
Create a contact and associate it with a company

### ISSUE THREAD

**Issue by retorquere** [HubSpot/hubspot-api-python#9]
When I create a new contact with `'company': 'Company name'`, it doesn't list it as an associated company in the contacts overview. How do I associate a contact with a company during/after create?

**Comment by atanasiuk-hubspot** [comment]
Hi, @retorquere! You probably need to create association between contact and company manually. 
Please check how this can be done in [Companies Sample App](https://github.com/HubSpot/hubspot-api-python/blob/master/sample-apps/companies-app/src/routes/associations.py#L83).

**Comment by retorquere** [comment]
Do you know in what property of the contact this would show up? I'm trying to keep a list of contacts synced with an associated company in HubSpot, so I'd need to test on this association before deletes/updates.

**Comment by atanasiuk-hubspot** [comment]
> Do you know in what property of the contact this would show up? I'm trying to keep a list of contacts synced with an associated company in HubSpot, so I'd need to test on this association before deletes/updates.

I'm not sure if "company" property is available during "contact" request.

What you can do is to request [associations](https://developers.hubspot.com/docs/api/crm/associations) for a contact. Example of using associations is [here](https://github.com/HubSpot/hubspot-api-python/blob/master/sample-apps/companies-app/src/routes/associations.py#L28).

**Comment by atanasiuk-hubspot** [comment]
Feel free to reopen the issue if any questions

**Comment by agustinleiraCDS** [comment]
Hello, to associate a contact with a company I am using the following code:
```
from hubspot import HubSpot
from hubspot.crm.contacts import PublicObjectSearchRequest, SimplePublicObjectInput, ApiException

def associateContactWithCompany(contact_id, company_id):
    try:
        return api_client.crm.contacts.associations_api.create(contact_id=contact_id, to_object_type="company", to_object_id=company_id, association_type="contact_to_company")
    except ApiException as e:
        print("Exception when calling associations_api->create: %s\n" % e)
```
Most of the times works fine, the issue comes when I create the user and the company at "the same time", sometimes this association doesn't work, I don't get any error but when I check in Hubspot's web console I see that the contact company is not the one I set, instead the one I chose I get the one that corresponds to the contact's email. I think there is a race condition, the association should be performing before the contact or the company is available on Hubspot. Have anyone had this kind of issue before? is there a way to overcome this?

Thanks
